### ISSUE TITLE
Tables aren't formatted correctly when viewing the website's dark theme 

### ISSUE THREAD

**Issue by colinkiama** [vala-lang/valadoc-org#389]
**Describe the bug**

If you view a page that uses tables with the site's dark theme styling, the table data is not formatted correctly. Parts of the table are unreadable.

**To Reproduce**
1. Toggle your web browser's color scheme preference to "Dark" 
2. Go to 'https://valadoc.org/glib-2.0/GLib.Time.strftime.html'
3. See the issue

**Expected behavior**
Rendered tables that match the dark styling and are completely readable.

**Screenshots**
![valadoc-unthemed-tables](https://github.com/vala-lang/valadoc-org/assets/16501024/8cd8cb68-7d73-4dfc-8f28-f65858c94dbe)

**Desktop (please complete the following information):**
 - OS: elementary OS 7
 - Browser: Google Chrome
 - Version: 114.0.5735.198

**Comment by lewisgoddard** [comment]
Adjusting the colors to a new baseline of #222222a seems to make them aggressively purple.

![image](https://github.com/vala-lang/valadoc-org/assets/831389/9bc15ec4-8fd5-4668-b362-4f5dfa304843)

```css
@media (prefers-color-scheme: dark) {
    .main_table {
        background: #335;
        border: 1px solid #77c;
    }
}
```
